<?php
namespace Leafwrap\PaymentDeals;

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Support\ServiceProvider;

class PaymentDealServiceProvider extends ServiceProvider
{
    public function boot(Kernel $kernel)
    {
        $this->loadRoutesFrom(__DIR__ . '/../routes/web.php');
        $this->loadViewsFrom(__DIR__ . '/../views', 'payment-deal');
        $this->loadMigrationsFrom(__DIR__ . '/../database/migrations');
    }

    public function register(): void
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->registerFacades();
    }

    protected function registerFacades(): void
    {
        $this->mergeConfigFrom(__DIR__ . '/../configs/payment_gateways.php', 'payment_gateways');
        $this->mergeConfigFrom(__DIR__ . '/../configs/currency_converters.php', 'payment_gateways');
        $this->app->singleton('PaymentDeal', fn($app) => new PaymentDeal($app));
    }
}
